import Loader from '../components/Loader';
import Resume from '../components/Resume';
import Head from 'next/head';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Resume | DERMOT OBRIEN</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Resume />
        </div>
    )
}